
services:
  # Backend Node.js API Service
  backend:
    image: mehedihasan11/myreactapp-node:latest  # Pulls the backend image from Docker Hub
    ports:
      - "5000:5000"  # Maps host port 5000 to container port 5000 (backend API access)
    depends_on:
      - mongo  # Ensures MongoDB container starts before the backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/expense-tracker  

  # Frontend React App Service (served via Nginx)
  client:
    image: mehedihasan11/myreactapp-frontend:latest  # Pulls the React app (built & served with Nginx)
    ports:
      - "3000:80"  # Maps host port 3000 to container port 80 (Nginx default)
    depends_on:
      - backend  # Waits for the backend to be up first

  # MongoDB Database Service
  mongo:
    image: mongo  # Uses the official MongoDB image from Docker Hub
    container_name: mongodb  # Optional: assigns a readable name to the MongoDB container
    restart: always  # Automatically restarts the container if it crashes
    ports:
      - "27017:27017"  # Maps MongoDB default port to host for tools like MongoDB Compass
    volumes:
      - mongo_data:/data/db  # Persists MongoDB data between restarts using a named volume

# Persistent storage volume for MongoDB data
volumes:
  mongo_data:
